### ISSUE TITLE
看不到效果

### ISSUE THREAD

**Issue by ASLhongxing** [WANZIzZ/WeChatRecord#2]
运行起来了，但是看不到效果，Toast”正在打开微信数据库，请稍候...”，之后就什么也没有了，是我的操作不对吗

**Comment by WANZIzZ** [comment]
我下午看看

**Comment by WANZIzZ** [comment]
你好，我这边测试了一下，在复制数据库的时候好像有些问题，我把路径改为SD卡就可以了，后续操作我这边测试都是正常的，你可以再看下打印的日志。

**Comment by ASLhongxing** [comment]
CoreSer类中的currApkPath，CoreService类中的currApkPath 我都已经改了"/data/data/com.wanzi.wechatrecord/"  但是要是没有效果，日志能打出来当前用户信息

**Comment by ASLhongxing** [comment]
1252729073，这是我工作qq，大神方便加一下指导指导
