### ISSUE TITLE
你好。copy出来的数据库打不开

### ISSUE THREAD

**Issue by ultraman521** [WANZIzZ/WeChatRecord#3]
![image](https://user-images.githubusercontent.com/16874325/44571565-b3a94680-a7b3-11e8-893d-e576b492141d.png)
但是微信文件夹里面的可以

**Comment by WANZIzZ** [comment]
这个应该是密码不正确，app里面直接能打开复制出来的数据库吗？

**Comment by ultraman521** [comment]
app里面能打开，但是用下面地址那个软件就不能。
直接把微信文件夹里面的数据库copy出来，就能打开

https://share.weiyun.com/5ahwbz1
