### ISSUE TITLE
如果聊天中发送文件能在本地中找到吗？

### ISSUE THREAD

**Issue by MartinMu2016** [WANZIzZ/WeChatRecord#4]
在聊天当中发送文件（如:zip）的话，能在本地找到资源路径吗？

**Comment by WANZIzZ** [comment]
可以找到，在/storage/emulated/0/tencent/MicroMsg/Download/ 这个目录下面

**Comment by MartinMu2016** [comment]
我尝试了下，别人发的文件下载了就有，但是我发的文件在Download中找不到。

**Comment by WANZIzZ** [comment]
哦，是这样的，接收到的文件再Download里面，发送的文件分两种，一种是微信文件，这种是在Download里面，一种是手机存储，这种是你发的文件的源地址。

**Comment by MartinMu2016** [comment]
那如果我是在微信聊天中，微信使用者发送给对方的文件这种操作，是无法获取到发送给对方的文件路径的？

**Comment by WANZIzZ** [comment]
我记得是可以，数据库里面有一个表，是存放这个信息的，appattach 这个表，你可以看下

**Comment by MartinMu2016** [comment]
好的，我找到了，在发送文件的时候，msg会生成一段xml文件，文件下载后，在里面找到attachid的字段和数据库的appattach的表中mediaSvrId字段对应，然后找到文件路径。
