### ISSUE TITLE
大佬,打开数据库的时候出错了!有解决方案吗?

### ISSUE THREAD

**Issue by lexluthors** [WANZIzZ/WeChatRecord#5]
Database: file is not a database: , while compiling: select count(*) from sqlite_master;
    net.sqlcipher.database.SQLiteException: file is not a database: , while compiling: select count(*) from sqlite_master;

**Comment by WANZIzZ** [comment]
这个提示是你复制出来的数据库文件有问题，你看下文件对不对

**Comment by lexluthors** [comment]
@WANZIzZ 文件是对的,这个问题很奇怪,第一次安装微信登录之后就可以.多试几次之后,这个问题必现。解决的办法只能卸载微信，重新安装才能解决。

**Comment by WANZIzZ** [comment]
微信版本是多少

**Comment by lexluthors** [comment]
@WANZIzZ 7.0.9

**Comment by WANZIzZ** [comment]
你的db文件大概有多大

**Comment by lexluthors** [comment]
@WANZIzZ 2.99m

**Comment by WANZIzZ** [comment]
我刚下了一个7.0.9的微信，测试了一下没什么问题，db文件是1.44m

**Comment by lexluthors** [comment]
@WANZIzZ 你多点几次，或者今天点几次之后，明天再试试就会出现

**Comment by lexluthors** [comment]
@WANZIzZ 请问重现了吗

**Comment by WANZIzZ** [comment]
没有 刚才我测试一下，可以正常获取聊天记录
