### ISSUE TITLE
本地资源路径不正确

### ISSUE THREAD

**Issue by HQLIE2018** [WANZIzZ/WeChatRecord#6]
WX_FILE_PATH + uinEnc + "/image2/" + weChatFile.name.substring(0, 2) + "/" + weChatFile.name.substring(2, 4) + "/" + weChatFile.name这个路径找不到图片，因为本地并没有由MD5.getMD5Str("mm$uin")生成的文件夹；
视频和语音也有上面的问题

**Comment by WANZIzZ** [comment]
在微信7.0.6的某一个小版本后，微信把这个地址改了，数据库的和存放文件的路径不一样了。

**Comment by HQLIE2018** [comment]
那现在有什么办法解决吗？

**Comment by WANZIzZ** [comment]
我看了下源码，大概是把获取到的 uinEnc 和 uin 又进行了一次转换 ，具体怎么转换的，目前我还没找到

**Comment by HQLIE2018** [comment]
那麻烦你找到后，及时回复一下，谢谢！

**Comment by WANZIzZ** [comment]
本地资源路径适配代码已经改好了。

**Comment by HQLIE2018** [comment]
感谢！

**Comment by joymingchen** [comment]
> 本地资源路径适配代码已经改好了。

找了好久，解决了我的问题，请问作者是咋知道这个资源路径的加密方式的？在逆向分析的哪部分找到的？我也是找了好久
