### ISSUE TITLE
android 10获取不到IMEI码

### ISSUE THREAD

**Issue by HQLIE2018** [WANZIzZ/WeChatRecord#7]
在android 10里面已经取不到IMEI码了，微信数据库的密码还是原来那种解开方式吗？

**Comment by WANZIzZ** [comment]
Android 10 的我没试过，不过低版本的目前还是这种方式。

**Comment by HQLIE2018** [comment]
Duplicate of #6 那个本地资源文件夹路径不正确有没有找到什么解决方案了

**Comment by WANZIzZ** [comment]
这个暂时还没有找到，找到了我会在README里面更新的

**Comment by WANZIzZ** [comment]
现已优化代码，不需要由App获取IMEI，本地资源路径获取也更新了。

**Comment by HQLIE2018** [comment]
"${MainAc.MM_ROOT_PATH}shared_prefs/beacontbs_DENGTA_META.xml"这种获取IMEI的方式是在安卓10的机型上使用的吗？我在8.1系统没看到beacontbs_DENGTA_META.xml这个文件

**Comment by WANZIzZ** [comment]
我这边的手机7.1.2、9.0版本的都有这个文件。是不是微信版本的问题？我这边都是最新版。

**Comment by HQLIE2018** [comment]
重新把微信打开就有了

**Comment by fengivy** [comment]
试了下，安卓Q是无法获取 Imei beacontbs_DENGTA_META.xml中也没有IMEI对应的字段，还是无法打开 ... @WANZIzZ

**Comment by fengivy** [comment]
试了下，安卓Q是无法获取 Imei beacontbs_DENGTA_META.xml中也没有IMEI对应的字段，还是无法打开 ... @WANZIzZ
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <long name="common_event_write_succ" value="59" />
    <string name="initsdkdate">2020-04-29</string>
    <string name="APPKEY_DENGTA">0M300GVKSH1IMBEK</string>
    <int name="GEN_QIMEI_TIMES" value="1" />
    <string name="querytimes">2</string>
    <long name="real_time_event_write_succ" value="0" />
    <string name="com.tencent.mm:tools_SDKVER_DENGTA">3.2.1.9-tbs</string>
    <string name="LAUEVE_DENGTA">2020-04-29</string>
    <string name="com.tencent.mm:appbrand2_SDKVER_DENGTA">3.2.1.7-tbs</string>
    <string name="APPVER_DENGTA">7.0.13.1640</string>
    <string name="GEN_QIMEI">2020-04-29</string>
    <string name="rqd_model">2020-04-29</string>
    <long name="on_app_first_install_time_com.tencent.mm:tools" value="1586325633262" />
    <string name="QIMEI_DENGTA">8b04252ec205251c</string>
    <string name="HEART_DENGTA">2020-04-29</string>
    <string name="on_qua_date">2020-04-29</string>
    <long name="real_time_event_calls" value="32" />
    <long name="real_time_event_upload_succ" value="31" />
    <string name="key_channelpath">channel.ini</string>
    <long name="on_app_first_install_time_com.tencent.mm:appbrand2" value="1578770314594" />
    <long name="common_event_calls" value="60" />
</map>

**Comment by WANZIzZ** [comment]
你试试 QIMEI_DENGTA 这个，我这里也没有Adnroid 10的手机 - -

**Comment by fengivy** [comment]
@WANZIzZ 试过了不行，微信可能改变了加密方式，对于android Q的，我在看源码，暂时没发现

**Comment by Manqijarly** [comment]
android 8.6.21  imei在这个文件中，WLOGIN_DEVICE_INFO.xml

**Comment by wzyboy** [comment]
我拿 Android 10 试了下， `CompatibleInfo.cfg` 这个文件为空（大小 0 字节），而 `beacontbs_DENGTA_META.xml` 也不存在。 `WLOGIN_DEVICE_INFO.xml` 这个文件是存在的，里面也有标为 `imei` 的字段，但是其实是个 Android ID 之类的东西，是 32 字符长度的小写 hex，并不是真正的 IMEI，拿它和 uin 拼起来算出来的密码也不能解密 `EnMicroMsg.db` …

**Comment by evil-hero** [comment]
给各位说一下，Android10获取不到IMEI，所以使用了1234567890ABCDEF，还是和以前一样的算法，完全没有变化，可能考虑到了兼容性，但是说实话我不是很能理解为什么不做更新呢

**Comment by wzyboy** [comment]
@evil-hero 神了。我试了下，拿 `1234567890ABCDEF` 当 IMEI，加上 UID 算出来的 MD5 的前七位还真就是 EnMicroMsg.db 的密码…

**Comment by evil-hero** [comment]
然后微信不知道从哪个版本开始，新安装只会在`.auth_cache`目录下记录明文`imei`了，其他的都是旧版本遗留文件。
建议Q以下获取`imei1` `imei2` `meid`一个个试，或者到`.auth_cache`下进行匹配，Q以上直接用`0123456789ABCDEF`就行了。
目前微信`targetSdk`是`28`，也就是`安卓9`，也说明微信没有正式适配安卓10。

**Comment by flyingshare** [comment]
如果系统是android10，并且微信属于系统应用，也就意味着微信可以获取到imei，经过验证，在android10上只要微信能够获取到imei，仍然是使用imei加密数据库的，这时使用1234567890ABCDEF是不可行的，那么问题来了，第三方应用获取不到imei，微信的imei又不知道保存在了哪里，微信目录中不存在beacontbs_DENGTA_META.xml，CompatibleInfo.cfg文件大小是0字节，systemInfo.cfg也没有可作为imei的字段，WLOGIN_DEVICE_INFO.xml中的imei标签也是不行的，.auth_cache目录下面是类似363b122c-528f-34df-8a04-46b6bab05515/1，363b122c-528f-34df-8a04-46b6bab05515/2......这样的文件，目前不知道怎么获取有效数据

**Comment by Rongrkang** [comment]
我5.1的系统微信版本7.0.22 填 1234567890ABCDEF也是可以打开的其他的imei1，imei2，meid都不行
.auth_cache 在哪个路径下面
