### ISSUE TITLE
数据库复制问题

### ISSUE THREAD

**Issue by HQLIE2018** [WANZIzZ/WeChatRecord#8]
除了把数据库复制一份，还有其它什么好的办法吗？数据库的数据会越来越多，复制会越来越慢，想要提高一下效率

**Comment by WANZIzZ** [comment]
目前是没有别的办法，因为如果直接打开微信数据库，然后再使用微信的话，微信会崩溃掉。

**Comment by HQLIE2018** [comment]
好的，倘若找到什么好的替代方案，麻烦告知一下

**Comment by WANZIzZ** [comment]
可以
